name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Cela sera déclenché lors d'un push sur la branche main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout du code source
    - name: Checkout code
      uses: actions/checkout@v2

    # Configuration de Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Connexion à Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Construction de l'image Docker
    - name: Build Docker image
      run: |
        docker build -t myusername/my-node-app:${{ github.sha }} .
    
    # Push de l'image Docker vers Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push myusername/my-node-app:${{ github.sha }}

